In [1]:
import numpy as np

In [2]:
u = np.array([1,2, 3])
v = np.array([4,-1,0])

In [3]:
u+v

array([5, 1, 3])

In [4]:
3*u + 2*v

array([11,  4,  9])

In [6]:
np.dot(u,v)

np.int64(2)

In [9]:
a = np.array([[1,2],[3,4]])
b = np.array([[-1,3],[4,2]])

In [10]:
a+b

array([[0, 5],
       [7, 6]])

In [11]:
np.matmul(a,b)

array([[ 7,  7],
       [13, 17]])

In [12]:
a@b

array([[ 7,  7],
       [13, 17]])

In [13]:
a.T

array([[1, 3],
       [2, 4]])

In [17]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [18]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [20]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
eigenvalues, eigenvectors = np.linalg.eig(c)
print("Eigenvalues: ", eigenvalues)
print("Eigenvectors: ", eigenvectors)

Eigenvalues:  [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigenvectors:  [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


SVD Matrix Decomposition

In [21]:
D = np.array([[1, 2, 3], [4, 5, 6]])
U, S, V_T = np.linalg.svd(D)
print("U: ", U)
print("S: ", S)
print("V_T: ", V_T)

U:  [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
S:  [9.508032   0.77286964]
V_T:  [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


Define a linear transformation that rotates a 2D vector by 90 degrees counterclockwise. Apply this transformation to the vector v = [2, 1].

In [22]:
theta = np.radians(90)  
rotation_matrix = np.array([[np.cos(theta), -np.sin(theta)],
                           [np.sin(theta), np.cos(theta)]])

v = np.array([2, 1])
transformed_vector = rotation_matrix @ v

print("Transformed vector:", transformed_vector)

Transformed vector: [-1.  2.]
